name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Randomblock1/theos-action@v1
      - run: make package FINALPACKAGE=1
      - run: |
          mkdir out
          find .theos -name "RGBX.dylib" -exec cp {} out/ \;
          ls -la out
      - uses: actions/upload-artifact@v4
        with:
          name: RGBX-dylib
          path: out/RGBX.dylib
